name: Create release from new tag

# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        go_version: ["1.20", "1.19"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go_version }}
      - run: go test -v -race ./...
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo GITHUB_REF is $GITHUB_REF
          BINARY_NAME=./bin/pkgfmt
          go build -o "$BINARY_NAME" -v -ldflags "-X main.Version=$GITHUB_REF"
      - name: Create GitHub release from tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/pkgfmt
