name: All builds
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.20", "1.19"]
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go_version }}
      - run: |
          go test -v -race ./...
          echo GITHUB_REF is $GITHUB_REF
